version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xMoM8BC3BeS2SwNCOIdw
      POSTGRES_DB: railway
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
